version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: encurtador-link-backend
    volumes:
      - ./:/var/www
    networks:
      - encurtador_link_default
    # depends_on:
    #   - db
    ports:
      - "8090:8090"
      - "6001:6001"
    restart: unless-stopped

  webserver:
    image: nginx:alpine
    container_name: nginx_server
    volumes:
      - ./:/var/www
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8081:80"
    networks:
      - encurtador_link_default
    depends_on:
      - app

  # db:
  #   image: mysql:8.0
  #   container_name: mysql_db
  #   environment:
  #     MYSQL_ROOT_PASSWORD: root
  #     MYSQL_DATABASE: root
  #     MYSQL_PASSWORD: root
  #   volumes:
  #     - dbdata:/var/lib/mysql
  #   ports:
  #     - "3307:3306"
  #   networks:
  #     - encurtador_link_default

networks:
  encurtador_link_default:
    driver: bridge

volumes:
  dbdata:
